### ISSUE TITLE
"smoothAdd" doc page has formatting issues

### ISSUE THREAD

**Issue by AvneeshSarwate** [Computer-Graphics-And-Pretty-Pictures/SculpturePark#1]
The text editor does not take up its fully allocated space

<img width="1381" alt="screen shot 2018-12-26 at 2 19 35 am" src="https://user-images.githubusercontent.com/2717770/50436586-a8c30780-08b4-11e9-98f8-0347854b2eb9.png">

**Comment by torinmb** [comment]
All the buttons in the editor still need to be turned into icons to conserve space + maybe have 'created by' on a separate line, but this should do the trick for now^
