### ISSUE TITLE
Ability to create, edit, and display GLSL and JS sculptures in the same environment 

### ISSUE THREAD

**Issue by PWhiddy** [Computer-Graphics-And-Pretty-Pictures/SculpturePark#11]

**Comment by torinmb** [comment]
This also fixed a bug in saving. works as intended where the user is notified if they don't save. they can go to another sculpture. then go back and the editor will still recognize that it wasn't saved. 

It could be useful to prevent someone from navigating to another route without saving / we could prompt them with the same pop up before they navigate away with unsaved changes.

**Comment by torinmb** [comment]
actually, wait that's a huge problem when you're editing a sculpture in /new. #41
