### ISSUE TITLE
Official name + icon + domain

### ISSUE THREAD

**Issue by torinmb** [Computer-Graphics-And-Pretty-Pictures/SculpturePark#27]

**Comment by PWhiddy** [comment]
Do we still have to call it shaderpark if were mainly pushing the js api?

**Comment by torinmb** [comment]
I liked the name shaderpark ofr the overall experience of the editor + museum of shaders, but now that it's also a framework I feel like we need to have a name that can encompass all of it. shaderpark doesn't feel like the name of a framework.
we need a name that wors as:
the __ framework,
the __ editor, and
the __ collection / gallery

**Comment by PWhids** [comment]
I guess this is closed?
